server:
  port: 8080

line.bot:
  channelToken: W9PTnUUu8amRFKeYIbUIfo5V7p6R0zCBBMfnmkWRVteJjNjKj2JELesSrdbJA2qoO9bLRpEFKkKvqQKmiRvd5iFEYHN01Vj0mIxBPrK+/gn+UrEPhysa3bGuVWzXSfffKdYflWLpLndYp/VDedBOpQdB04t89/1O/w1cDnyilFU=
  channelSecret: 1c70964615e6d067440f515c6fef46a9
  handler.path: /callback

# log config
logging:
  config:
    classpath: logback.xml
  level:
    com:
      example:
        mapper: debug
